version: "3.8"
services:
  app:
    image: "docker-nextjs-dev"
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./config:/app/config
      - ./constants:/app/constants
      - ./hooks:/app/hooks
      - ./pages:/app/pages
      - ./public:/app/public
      - ./redux:/app/redux
      - ./services:/app/services
      - ./styles:/app/styles
      - ./types:/app/types
      - ./utils:/app/utils
